### ISSUE TITLE
Span attributes: array of primitives

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#111]
Need to add support for attribute values being arrays of primitives.

**Comment by bryannaegele** [comment]
I added this in the exporter with the tuple support. Is this not supported by the SDK?

**Comment by tsloughter** [comment]
@bryannaegele right, I don't think it was added to the SDK but I didn't double check before opening this...

**Comment by bryannaegele** [comment]
OK. We're good on this _except_ we aren't type checking or enforcing arrays (lists or tuples) are homogeneous.

**Comment by tsloughter** [comment]
Eh, I don't think we should bother enforcing that inline. It'll be enforced at the time of export, right?

**Comment by tsloughter** [comment]
Closing this as nothing needs to be done. The only thing possibly needed is to make the `attribute_value` type explicit, right now it is `any()`.
