### ISSUE TITLE
Checking for correct Behaviour in module_info/0 in API

### ISSUE THREAD

**Issue by ioolkos** [open-telemetry/opentelemetry-erlang#135]
Exploring things a little bit, I noticed that I can't set tracers when the `.beam` files are stripped in a `prod` release, I think.
There reason is the check for the correct Behaviour here:

https://github.com/open-telemetry/opentelemetry-erlang/blob/618ccd452d601679e9aae419a38d247474ae78cb/apps/opentelemetry_api/src/opentelemetry.erl#L376

The `module_info/0` call might look like this, giving an empty attributes list:

```erlang
1> otel_tracer_default:module_info().
[{module,otel_tracer_default},
 {exports,[{start_span,3},
           {start_span,4},
           {with_span,3},
           {with_span,4},
           {b3_propagators,0},
           {w3c_propagators,0},
           {module_info,0},
           {module_info,1}]},
 {attributes,[]},
 {compile,[]},
 {native,false},
 {md5,<<229,142,94,192,207,250,193,205,25,119,87,154,29,
        226,111,166>>}]
2> 
```
Do you think this is a correct assessment, and is it a case that matters?

**Comment by tsloughter** [comment]
Argh, yes, we should remove this check.

**Comment by ioolkos** [comment]
Ok, something like this then:

```Erlang
-spec set_default_tracer(tracer()) -> boolean().
set_default_tracer(Tracer) ->
    persistent_term:put({?MODULE, default_tracer}, Tracer).

-spec set_tracer(atom(), tracer()) -> boolean().
set_tracer(Name, Tracer) ->
    persistent_term:put({?MODULE, Name}, Tracer).

-spec set_default_meter(meter()) -> boolean().
set_default_meter(Meter) ->
    persistent_term:put({?MODULE, default_meter}, Meter).

-spec set_meter(atom(), meter()) -> boolean().
set_meter(Name, Meter) ->
    persistent_term:put({?MODULE, Name}, Meter).
```

**Comment by tsloughter** [comment]
It can still check if the module exists, even if it doesn't depend on the tracer behaviour being there.

**Comment by tsloughter** [comment]
I added a fix here https://github.com/open-telemetry/opentelemetry-erlang/pull/137

**Comment by ioolkos** [comment]
Thanks! I'll test it.

**Comment by ioolkos** [comment]
Behaves as expected now. Thanks.
