### ISSUE TITLE
Building opentelemetry_exporter as a dependency

### ISSUE THREAD

**Issue by ioolkos** [open-telemetry/opentelemetry-erlang#142]
I've noticed something which might be related to this issue, or not: https://github.com/open-telemetry/opentelemetry-erlang/issues/140:

I can't seem to build a release when one of the apps in the release has `opentelemetry_exporter` as a dependency (this is while I try to explicitly fetch the `opentelemetry_exporter` git subdirectory in its `rebar.config`)

```
===> Compiling opentelemetry_exporter
===> Compiling _build/default/lib/opentelemetry_exporter/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl failed
_build/default/lib/opentelemetry_exporter/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl:246: undefined macro 'OTEL_STATUS_UNSET'

_build/default/lib/opentelemetry_exporter/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl:192: function to_otlp_status/1 undefined
_build/default/lib/opentelemetry_exporter/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl:245: spec for undefined function to_otlp_status/1

make: *** [Makefile:26: rel] Error 1
```
Rebar normally builds apps (dependencies) in `_build/default/lib/my_app/ebin`. For opentelemetry-erlang I see paths like this `_build/default/lib/opentelemetry_api/apps/opentelemetry_api/ebin`.

I don't know whether this is the reason `opentelemetry_exporter` doesn't seem to have access to the .hrl files of the API.

Might be a super basic thing I'm missing here... thanks much for any clues.

**Comment by tsloughter** [comment]
So you are building with rebar3? If so this is unrelated to #140

**Comment by tsloughter** [comment]
The fact that it isn't saying it can't find the header file makes me wonder if its something else.

Can you clean everything out and build from scratch to make sure there isn't some other (old) version of the header without `OTEL_STATUS_UNSET`?

**Comment by ioolkos** [comment]
Thanks! always was a clean build, but your remark made me find the issue...zipkin lib kept the api locked to a commit before those changes, and the actual API changes are in your last commit... argh :)

This is great, thanks for your help & time!
