### ISSUE TITLE
Wrong module name for `add_event(s)` macro

### ISSUE THREAD

**Issue by ioolkos** [open-telemetry/opentelemetry-erlang#144]
https://github.com/open-telemetry/opentelemetry-erlang/blob/bcd54678ef67517c31f65b780f03b752b155a950/apps/opentelemetry_api/include/otel_tracer.hrl#L36

`otel_span:add_event/2` does not exist, guess this should go to `otel_tracer:add_event/2`.

**Comment by tsloughter** [comment]
No, looks like it should be:

```erlang
define(add_event(Name, Attributes), 
        otel_span:add_event(?current_span_ctx, Name, Attributes)).
```

**Comment by ioolkos** [comment]
Ah, okay, thanks.

**Comment by tsloughter** [comment]
Do you have a PR or should I open one?

**Comment by ioolkos** [comment]
Had not yet a PR, thanks for fixing it! :)
