### ISSUE TITLE
Getting started guide with stdout exporter

### ISSUE THREAD

**Issue by CrowdHailer** [open-telemetry/opentelemetry-erlang#160]
I am discovering getting started with open telemetry is not easy. Or at least that's how I'm finding it.

Is there any getting started guide with erlang code as the example? Is it sensible to start a new project with the stdout exporter so I don't have to set up a collector service? A guide, or even a link to a guide, that covered these points would be really helpful

**Comment by tsloughter** [comment]
Sorry about that, I'm aware. There isn't a guide yet but I'm going to be writing one for https://opentelemetry.io/docs/ to match the other languages and that will be also included in the hexdocs.

And yea, sensible to start with the stdout exporter, that is the "example" in the `config/sys.config`.

**Comment by CrowdHailer** [comment]
Ok, that's good to know. I'm still fighting with it, have switched to setting up the JavaScript in the browser. although the docs are not very update for that either and reference node, when talking about the brower in several places.

If you want me to have a look at any drafts for the guide I'll be very happy to.
We should be opensourcing one of our services that uses open telemetry next week so there will at least be an example. (although as it'll be Gleam maybe not very useful as an example)

**Comment by tsloughter** [comment]
Thanks, will definitely send the drafts your way.

A gleam example would be awesome to have in https://github.com/opentelemetry-beam/opentelemetry-examples

**Comment by tsloughter** [comment]
This was added on https://opentelemetry.io/docs/erlang/getting-started/
