### ISSUE TITLE
Implement "Named Tracers and Meters"

### ISSUE THREAD

**Issue by z1c0** [open-telemetry/opentelemetry-erlang#17]
The "Named Tracers and Meters" RFC (https://github.com/open-telemetry/oteps/blob/master/text/0016-named-tracers.md) has been approved and was added to the specification (open-telemetry/opentelemetry-specification#264).

Please make sure to also update the documentation if necessary (tracer, meter creation).

OpenTelemetry language repositories now need to implement this mechanisms.

**Comment by tsloughter** [comment]
Thanks, this is complete now.
