### ISSUE TITLE
Env variable OTEL_EXPORTER

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#170]
Default: `otlp`

Known values for OTEL_EXPORTER are: "otlp", "jaeger", "zipkin", "prometheus", "otlp_span", "otlp_metric".

Note: "otlp" is equivalent to "otlp_span,otlp_metric".

**Comment by hauleth** [comment]
What should happen when value of the `OTEL_EXPORTER` is present but outside of the given set? Also, should we allow configuring that via sys config and if we do, then which one should take preference?

My take on this is:

- if variable is there and contains unknown value, then we should emit `warning` level log message and fallback to default
- we should allow configuring that via `sys.config` but environment variable takes precedence if present

**Comment by tsloughter** [comment]
We do already allow configuring in sys.config.

I think environment variable should take precedence.

Agreed about how to handle a value outside the given set.

**Comment by tsloughter** [comment]
Resolved with #207
