### ISSUE TITLE
Link to archived project in the README

### ISSUE THREAD

**Issue by CrowdHailer** [open-telemetry/opentelemetry-erlang#171]
https://github.com/open-telemetry/opentelemetry-erlang/blob/master/README.md#design

The section linked above says `If you are instrumenting a project your application should only depend on the OpenTelemetry API application.` However following that link takes you to an archived project that links back around to the original project.

Unclear what the correct course of action is

**Comment by tsloughter** [comment]
Damn, thanks, I'll make a PR.
