### ISSUE TITLE
Urgent help needed .. compatibility broken with erlang.mk

### ISSUE THREAD

**Issue by SoniCoder** [open-telemetry/opentelemetry-erlang#178]
Post API and SDK merge, unable to compile the project using erlang.mk since erlang.mk doesn't support rebar3's git_subdir feature yet and because of this the required beam files aren't formed.

Please suggest the best alternative than moving to rebar3 since our build chain heavily relies on erlang.mk usage. Shall I fork the repo back to separate API and SDK repos so that erlang.mk compatibility is restored?

Any sort of help is appreciated.

Thanks!

**Comment by tsloughter** [comment]
I guess the only alternative to moving to rebar3 or adding support to erlang.mk is to stick to the hex packages -- or, yes, keeping your own separated repos in sync somehow.

**Comment by SoniCoder** [comment]
It seems that erlang.mk does support it as another fetch method which I was not aware of: https://github.com/ninenines/erlang.mk/issues/917

Thanks for help, I'll close it

**Comment by jek-bao-choo** [comment]
For anyone searching you could use hex to get all three opentelemetry libraries required. The below versions are tested with Erlang/OTP v22.

```
PROJECT = hello_world
PROJECT_DESCRIPTION = Cowboy Hello World example
PROJECT_VERSION = 2

DEPS = cowboy opentelemetry_api opentelemetry opentelemetry_exporter opentelemetry_cowboy
dep_cowboy_commit = master

# OpenTelemetry dependencies
dep_opentelemetry_api = hex 1.0.3
dep_opentelemetry = hex 1.0.5
dep_opentelemetry_exporter = hex 1.0.4
dep_opentelemetry_cowboy = hex 0.2.1

REL_DEPS = relx

include ./erlang.mk
```
