### ISSUE TITLE
Exporter crashes Elixir application when protocol is set to grpc

### ISSUE THREAD

**Issue by dwebster17** [open-telemetry/opentelemetry-erlang#180]
Currently running `opentelemetry` in an Elixir 1.10.1 application. I'm noticing that when the `protocol` is set to `grpc`, `opentelemetry_exporter:init/1` fails because the `gproc_pool` process hasn't been started when we hit these lines:

https://github.com/open-telemetry/opentelemetry-erlang/blob/ea02818322e37b52d26e00777a1cf07681f40cf9/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl#L27

The `grpcbox_channel` module calls:
```erlang
gproc_pool:new(Name, BalancerType, [{size, length(Endpoints)}, {autosize, true}]),
```

which yields this error:

```
=ERROR REPORT==== 25-Nov-2020::23:07:56.228545 ===
** State machine opentelemetry_exporter terminating
** When server state  = {undefined,undefined}
** Reason for termination = exit:{noproc,
                                  {gen_server,call,
                                   [gproc_pool,
                                    {new,opentelemetry_exporter,round_robin,
                                     [{size,1},{autosize,true}]}]}}
** Callback mode = undefined
** Stacktrace =
**  [{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},
     {gproc_pool,call,1,
                 [{file,"/drone/src/github.com/postmates/knapsack/commit/671d270d1ee59305d6a39d975b4818dc09f42d9e/deps/gproc/src/gproc_pool.erl"},
                  {line,632}]},
     {grpcbox_channel,init,1,
                      [{file,"/drone/src/github.com/postmates/knapsack/commit/671d270d1ee59305d6a39d975b4818dc09f42d9e/deps/grpcbox/src/grpcbox_channel.erl"},
                       {line,76}]},
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,714}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
``` 

I'm honestly not sure if this issue is isolated to how Elixir does [releases](https://hexdocs.pm/mix/Mix.Tasks.Release.html), or if this is universal (I'd guess the former). Considering the `opentelemetry_exporter` module doesn't implement the `application` behaviour, I'm wondering if `mix` skips it when it is trying to start up dependencies in order, and as a result, the `grcpbox` and `gproc` processes aren't correctly started by the time they're needed?

Any thoughts / help here would be greatly appreciated!

**Comment by dwebster17** [comment]
This diff fixes it https://github.com/dwebster17/opentelemetry-erlang/commit/225c6eac0fb31fa649e7fd984ba382719ffd6a05

Although I'm not sure that pattern is encouraged / something we'd actually want to do.

**Comment by tsloughter** [comment]
@dwebster17 yea, I can't decide on what is best to do here either. I'm now thinking it should just log a message about failing and revert to using `http_protobuf`. I'll send a PR with that idea.

**Comment by tsloughter** [comment]
Oh wait, I miunderstood. I thought the issue was failing in `{ok, ChannelPid} = `, `grpcbox` is listed in the app files applications list I don't know how it couldn't be started...

**Comment by tsloughter** [comment]
If you aren't using the latest Elixir, 1.11, then I'd suspect it may be a release problem in previous versions and we could close this?
