### ISSUE TITLE
Undefined values and OTLPResourceNoServiceName - How to fix this?

### ISSUE THREAD

**Issue by mdurand54** [open-telemetry/opentelemetry-erlang#186]
Hello,

We are trying to implement distributed tracing with OpenTelemetry in our application. However, we are somewhat blocked because some values remain `undefined`.

This is what we get in the debugging console:
``` bash
*SPANS FOR DEBUG*
{span,212375836085442301867126075005776437348,3666090743276998234,undefined,
      undefined,<<"span_name">>,'INTERNAL',-576460742558133905,
      -576460742557915574,
      [{<<"id">>,<<"some_id">>},
       {<<"operation">>,<<"Source_Index">>},
       {<<"app.name">>,<<"App_Name">>}],
      [],[],undefined,1,false,
      {instrumentation_library,<<"serve">>,<<"0.0.1">>}}
```

We start a span as follows:
``` elixir
span = Tracer.start_span("span_name")
Span.set_attribute(span, "app.name", "App_Name")
Span.set_attribute(span, "operation", "Source_index")
Span.set_attribute(span, "id", "some_id")
```

The values we set in the configuration of our OpenTelemetry Collector work, but it is impossible to know what these `undefined` values are. Moreover, our traces have these names: `OTLPResourceNoServiceName: App_Name::Source_Index::some_id`.

How not to get `undefined` values or `OTLPResourceNoServiceName`?

Thanks!

**Comment by tsloughter** [comment]
What values remain undefined? Do you mean you are seeing some attributes in the tracing receiver you are using with value "undefined"? What receiver are you using?

For OTLPResourceNoServiceName I'm guessing you need to set the name and version either with the OS env like:

```
OTEL_RESOURCE_ATTRIBUTES="service.name=somename,service.version=1.1.1"
```

You can also do it with application environment under `opentelemetry` key `resources` https://github.com/open-telemetry/opentelemetry-erlang/blob/master/apps/opentelemetry/src/otel_resource_app_env.erl#L30

**Comment by mdurand54** [comment]
Indeed I have not been entirely clear. Your solution for `OTEL_RESOURCE_ATTRIBUTES` helps us.
Thank you for your solution and your speedy response!

Regards.
