### ISSUE TITLE
Add service.name fallback

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#191]
https://github.com/open-telemetry/opentelemetry-specification/pull/1269/files

**Comment by pallix** [comment]
Does this issue mean it is not possible to set the `service_name` currently?

**Comment by tsloughter** [comment]
No, it should be. You can set it in the application environment or OS environment variable. See the docs in `otel_app_resource_env`:

```
%%     [{service, #{name => "service-name",
%%                  namespace => "service-namespace"}]
```

**Comment by pallix** [comment]
Thanks, I managed to do it like this:

```
config :opentelemetry, :resource,
  service: %{name: "myserver", namespace: "mynamespace"}
```

I am documenting this here, in case somebody is looking for it.

**Comment by indrekj** [comment]
> I am documenting this here, in case somebody is looking for it.

Not sure if this got documented - I didn't manage to find it. Finally found this issue which helped me to understand how to change the service name.
