### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-erlang#195]
I apologize if there is already an open issue for this. I searched and did not find one. This should be done in this repo and also https://github.com/open-telemetry/opentelemetry-erlang-api.

For more information see https://github.com/open-telemetry/community/issues/402

**Comment by tsloughter** [comment]
@dyladan I recall the plan being to wait until Github made this simpler. It is still a manual process that doesn't redirect the current default branch to `main`? I'm fine doing it manually and not having the redirect, just wanted to check before moving forward.

**Comment by bogdandrutu** [comment]
> It is still a manual process that doesn't redirect the current default branch to main

If you go to Settings -> Branches and change the name of the default you will see that github automatically changes the default for upstream and branch protection rules. It does not change for forks and for CI actions that is the manual part.

**Comment by tsloughter** [comment]
Thanks. Done.
