### ISSUE TITLE
Setting an additional header on endpoint definition

### ISSUE THREAD

**Issue by kdisneur** [open-telemetry/opentelemetry-erlang#202]
I configured this library to send traces through GRPC locally to a Jaeger-Opentelemetry container and it worked well.

Now, I tried to switch from my local Jaeger to NewRelic, the difference being they ask for an `Api-Key` in a header to authenticate the request.

I would like to avoid deploying an OpenTelemetry Collector application as I was planning to just run my application on Heroku.

I was not able to find a way to do it with the current implementation. Can you give me some pointer or at least confirm it's not supported right now?

Thanks for your help 🙇

**Comment by tsloughter** [comment]
Good question... I'd be curious what other languages do for this. Maybe it is just that the exporter accepts a list of additional headers.

What exporter are you using? I didn't think there was a Jaeger exporter?

**Comment by kdisneur** [comment]
I use the opentelemetry_exporter defined in this repository. As it’s only for my local development, I just send all the traces to the [experimental version of jaeger that supports opentelemetry](https://www.jaegertracing.io/docs/1.21/opentelemetry/).

i planned to use the same opentelemetry_exporter for new relic, it should only require an additional header in the HTTP request in order to work 🤞. 

i tried to read the source a little bit and discovered I could set the key channel_opts in the configuration (alongside endpoints and protocols) to define my own unary interceptor.
I don’t know a lot about gRPC but I think this the common place where people put their authentication logic?

i was able to intercept the requests but I’m now a bit stuck as I have no idea I how to update the request before calling the next handler

**Comment by kdisneur** [comment]
> Maybe it is just that the exporter accepts a list of additional headers.

If I understand properly the spec, you are right, they expect the exporters to support headers: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options

**Comment by tsloughter** [comment]
Oh cool, ok, I didn't realize Jaeger or New Relic supported the OpenTelemetry exporter.

Auth is probably just headers. Tho I might have to add authenticated channels to grpcbox, shouldn't be much work. But just adding the ability to append some header would be the simplest.

**Comment by tsloughter** [comment]
Ah, yup. Will get that added.

**Comment by tsloughter** [comment]
This was added in #206 and I'll try to have a 0.6.1 or 1.0-rc1 release out tonight or tomorrow.

**Comment by kdisneur** [comment]
Thank you very much @tsloughter 🙇 🙇
