### ISSUE TITLE
Upgrade ex_doc and drop cmark

### ISSUE THREAD

**Issue by chulkilee** [open-telemetry/opentelemetry-erlang#204]
Separated from #176
Related: #150

- Recent ex_doc provides compile-time check for bad reference (e.g. link for undefined type)
- earmark + ex_doc provides better navigation (e.g. sections)

Also note that syntax highlight in `README.md` are broken even with this change:

* ex_doc with earmark: elixir working / erlang not working
* ex_doc with cmark: elixir not working / erlang working

**Comment by garthk** [comment]
See also: https://github.com/open-telemetry/opentelemetry-erlang/pull/227#issuecomment-804823690, https://github.com/wojtekmach/opentelemetry-erlang/commit/b15e27a089b9ae4eef83433a953737f5453de2dd

> yea, ex_doc can not be upgraded any way because it loses cmark support -- no stable version of ex_doc means no stable support for plugins for it and every version can break :(. We need to move to that need doc generation I showed you from woj instead

**Comment by wojtekmach** [comment]
Thanks @garthk. The doc generation script that Tristan referred to is based on what we have been using for some time on hex_core. In the meantime ExDoc 0.24.0 and Erlang 24.0-rc1 have been released so I just updated the script accordingly:

https://github.com/hexpm/hex_core/blob/7a4ad2865790eedd140d6ebd18d9c1707fc93435/docs.sh

We'd love to support Cmark but we need it to return the AST which is not trivial to add (unless you know C well haha.)

**Comment by garthk** [comment]
Cheers, @wojtekmach!

@chulkilee how bad is the “not working”? If it's just that syntax highlighting is absent in the README in particular, perhaps that's not worth indefinitely delaying the upgrade.

**Comment by chulkilee** [comment]
👍 to update ex_doc with earmark, even it does not support erlang syntax highlights in README, since 1) newer ex_doc has more features for not only usability but also correctness of doc and 2) the broken erlang syntax should be fixed anyway in short term (as ex_doc for erlang is coming).

**Comment by tsloughter** [comment]
This has been resolved (I think) by the recent change to use the `ex_doc` escript for the API docs as well. Still need to remove the `ex_doc` dep from the API's mix.exs, but it isn't used.
