### ISSUE TITLE
How to enable debug logs for the lib?

### ISSUE THREAD

**Issue by benonymus** [open-telemetry/opentelemetry-erlang#214]
Hey, 
I am trying to use this lib, and with otel_collector but nothing seems to show up at the end of the pipeline.
Someone suggested to enable debug logs for the SDK, because geenrally if the export fails there would be a debug log.
How does one doe that?

Something with OTEL_LOG_LEVEL ? If so what value and where to put it in an elixir project?

Thank you

**Comment by tsloughter** [comment]
`OTEL_LOG_LEVEL` doesn't do anything yet so the opentelemetry logs are the same as the level of the rest of your system.

There is an info log if the exporter throws an exception or it receives back a non-200 response if you are using the `http_protobuf` protocol. There isn't handling of error responses for the grpc protocol yet.

**Comment by benonymus** [comment]
@tsloughter Thanks, I am trying to find if we have such a log, could you maybe send an example of what the log might look like?

Maybe just to verify that I am using the lib correctly, I am trying to have it working with an otel_collector sidecar, is there any way to verify if the lib is trying to send the traces?

In the mix file I added `:opentelemetry` as an extra_application, I am calling `OpenTelemetry.register_application_tracer/1` in the application file, and the span part should be fine, am I missing anything on this side?

**Comment by tsloughter** [comment]
Best I can do right now is:

https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry/src/otel_batch_processor.erl#L293

https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl#L110

I can't help more right now and won't be around again for a while. I'd suggest Elixir slack channel #opencensus (I know, haven't moved to a new channel yet) and particurlarly @marcdel who has been configuring the exporter recently.

Also try my PR https://github.com/open-telemetry/opentelemetry-erlang/pull/213

**Comment by tsloughter** [comment]
I've merged my PR #213 to `main`. so you can now just try the latest commit from this repo.

**Comment by benonymus** [comment]
@tsloughter Thanks!
Do I understand right that by default the lib is sending the traces on localhost:4317 on http and that is what I should feed to my receiver?
And that I can overwrite this by setting the otlp_endpoint or otlp_traces_endpoint in my config?
I was listening on grpc on localhost:55680

**Comment by benonymus** [comment]
When I am trying to compile with the main branch I am getting this error: 
`Unchecked dependencies for environment dev:
* opentelemetry (https://github.com/open-telemetry/opentelemetry-erlang - origin/main)
  could not find an app file at "_build/dev/lib/opentelemetry/ebin/opentelemetry.app". Another app file was found in the same directory "_build/dev/lib/opentelemetry/ebin/otel_elixir_tests.app", try changing the dependency name to :otel_elixir_tests
** (Mix) Can't continue due to errors on dependencies`

**Comment by tsloughter** [comment]
@benonymus regarding the error building building, what do your mix dep look like? Are you including the sparse dep option like in https://github.com/open-telemetry/opentelemetry-erlang#git-dependencies

**Comment by tsloughter** [comment]
And yes, you can set ` otlp_endpoint` or  `otlp_traces_endpoint `

Just be sure you set them under the `opentelemetry_exporter` application. You can also use environment variables, `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` -- this value takes precedence.

**Comment by benonymus** [comment]
Hey thanks for the answer again I have it like this:
{:opentelemetry, "~> 0.6.0"}

**Comment by benonymus** [comment]
And what port should I be adding ot the receiver if I don't set the otlp_endpoint?
4317?

**Comment by tsloughter** [comment]
What dep do you list for the api? The error you get is really confusing, its seeing a module that is not only in a test directory but isn't even in any of the actual applications, I have no idea how itsgetting there.

But I would also suggest switching to the `main` branch of all deps, instead of the hex deps like you have right now, there are fixes in `main`. 

The port should be 4317 by default if you use the latest `main` branch.

**Comment by benonymus** [comment]
Thanks I am trying now!

I added this: 
`      {:opentelemetry_api,
       github: "open-telemetry/opentelemetry-erlang",
       sparse: "apps/opentelemetry_api",
       override: true},
      {:opentelemetry,
       github: "open-telemetry/opentelemetry-erlang", sparse: "apps/opentelemetry", override: true},`

In my config should I be listening to:           \
http:
    endpoint: "localhost:4317"
?

**Comment by tsloughter** [comment]
in the config under the section for `opentelemetry_exporter` you should have `otlp_traces_endpoint: 'http://localhost:4317`.

Note you'll also need in your deps:

```
{:opentelemetry_exporter, github: "open-telemetry/opentelemetry-erlang", sparse: "apps/opentelemetry_exporter", override: true}
```

**Comment by benonymus** [comment]
Ok I have all 3 of those deps, I added the config you suggested, do I need extra_applications: [:opentelemetry] ? or not then?
And listening on port 4317 in my collectors receiver.

**Comment by benonymus** [comment]
But what do these otlp_endpoint or otlp_traces_endpoint  do if you need the exporter and need to set the path there?

**Comment by tsloughter** [comment]
`otlp_traces_endpoint` accepts a path while `otlp_endpoint` will append the path `v1/traces` to the url you give.

And if its not working can you post the config you have? 

Also since I'm going to be gone again for the day soon you can also get help in slack.

I can hopefully work on docs for the exporter tomorrow morning in the couple hours I have each day.

**Comment by benonymus** [comment]
Thank you for all the help, the docs would be very useful!
It still doesn't seem to work.

Config in the app:

Deps:
`      {:opentelemetry_api,
       github: "open-telemetry/opentelemetry-erlang",
       sparse: "apps/opentelemetry_api",
       override: true},
      {:opentelemetry,
       github: "open-telemetry/opentelemetry-erlang", sparse: "apps/opentelemetry", override: true},
      {:opentelemetry_exporter,
       github: "open-telemetry/opentelemetry-erlang",
       sparse: "apps/opentelemetry_exporter",
       override: true},`

Config:

`config :opentelemetry_exporter,
  otlp_traces_endpoint: 'http://localhost:4317'`

In the application I am registering the tracer for the app:

`OpenTelemetry.register_application_tracer(:mobility_service)`

And in the code I have: 
`OpenTelemetry.Tracer.with_span "prototype_span_mobility" do {magic here} end`

Now the otel_collector config:

I want to export to elastic so I am using the contrib image:
`        - name: otel-collector
          args:
          - "--config=/conf/otel-collector-config.yml"
          image: otel/opentelemetry-collector-contrib:latest
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
          - containerPort: 55680 # Default endpoint for OpenTelemetry receiver.
          - containerPort: 8888  # Default endpoint for querying metrics.
          volumeMounts:
          - name: otel-collector-config-vol
            mountPath: /conf
  #        - name: otel-collector-secrets
  #          mountPath: /secrets
          livenessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.
          readinessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.`

config loaded as such:

`        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yml
          name: otel-collector-config-vol`

and the config: 

`apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "localhost:55680"
          http:
            endpoint: "localhost:4317"
    processors:
      batch:
    extensions:
      health_check: {}
    exporters:
      elastic:
        apm_server_url: 'url here'
      logging:
        logLevel: debug
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [elastic, logging]
`

**Comment by tsloughter** [comment]
@benonymus sorry I don't recall if we discussed this elsewhere and it got resolved and can be closed?

**Comment by benonymus** [comment]
Hey @tsloughter, 

Since then I moved on from that project, as I recall we decided to go in another direction.

**Comment by tsloughter** [comment]
@benonymus ok, thanks for the update. Do you mind saying what direction you went, a different tracing library? Always helpeful to know what we can do better. Tho note that 1.0 was a year after this issue was opened, so hopefully things have gotten substantially better here :)

**Comment by benonymus** [comment]
It's been a while since I left the project, but I think at the time we just kept using the opencensus library, that we wanted to replace with this.

**Comment by tsloughter** [comment]
Aah, ok. That makes perfect sense. This project replaces OpenCensus but has to first catch up with it in terms of features and stability :). I think we are there for tracing now, but metrics are still in the works. If you speak to anyone in that project again please let them know. Thanks again!

**Comment by benonymus** [comment]
Hey,

I think we abandoned this approach at the time, for another solution.

Feel free to close it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
