### ISSUE TITLE
How do we specify the instrumentation_library in Elixir integrations?

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#219]
I'm not having much luck getting anything into my outbound spans' `instrumentation_library`.

**Comment by tsloughter** [comment]
It is done automatically or with `register_tracer`.

**Comment by tsloughter** [comment]
@garthk was this resolved or is there still confusion?

**Comment by garthk** [comment]
I'm still confused. Let's say I'm trying to do so for `OpenTelemetry.Tesla`. I can't get my application version at compile time, so I wait until I get called and then:

```elixir
  @impl true
  def call(%Env{} = env, next, opts) do
    {:ok, vsn} = :application.get_key(:opentelemetry_tesla, :vsn)
    OpenTelemetry.register_tracer(:opentelemetry_tesla, vsn)
```

… which takes 1–2ms the first time, and 150-200µs the times after that, so maybe I want to find a way to call it only once. Anyhow, I then use the `Tracer.with_span/3` macro… and I still get `instrumentation_library: :undefined` in the output `span` record.

Digging in a little, I might also:

```elixir
  @impl true
  def call(%Env{} = env, next, opts) do
    OpenTelemetry.register_application_tracer(:opentelemetry_tesla)
```

… which takes about the same amount of time. Nice, but I feel like I guessed rather than knew what I was doing. Assuming my second example is correct, how about I file a PR to add an example to the doc-strings? How could I change my first example so it is also correct?

**Comment by tsloughter** [comment]
Oh, definitely don't want to do it on every call. Does Tesla not have an `init` for middlewares? Like in Elli I use its startup callback to register the tracer for the middleware: https://github.com/opentelemetry-beam/opentelemetry_elli/blob/master/src/otel_elli_middleware.erl#L50-L51

If Tesla has no way of doing something similar then I think we need to talk to them about adding it.

A hack to do in the mean time, until such a feature can be added to Tesla, would be to make the `opentelemetry_tesla` app one with an empty supervision tree so it can be done at startup of the app.

**Comment by garthk** [comment]
Yeah, I'll give that a shot.

**Comment by garthk** [comment]
Oh, I should swing back around and sneak up on making the docs clear: what's the job of `register_tracer`?

**Comment by tsloughter** [comment]
Applications are automatically registered with their instrumentation library now so closing this.
