### ISSUE TITLE
otel_ctx:set_value/2 has incorrect function specification

### ISSUE THREAD

**Issue by jakobsvenning** [open-telemetry/opentelemetry-erlang#222]
I believe that the function specification of [otel_ctx:set_value/2](https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry_api/src/otel_ctx.erl#L59) is incorrect. `otel_ctx:set_value/2` has the type specification `-spec set_value(term(), term()) -> ok`. `otel_ctx:set_value/2` returns the value returned by [erlang:put/2](https://erlang.org/doc/man/erlang.html#put-2). However, `erlang:put/2` returns the atom `undefined` on success, not the atom `ok`. Therefore, the function specification of `otel_ctx:set_value/2` should be `-spec set_value(term(), term()) -> undefined`.

**Comment by tsloughter** [comment]
Thanks, you are right.

**Comment by tsloughter** [comment]
This was resolved, it now always returns `ok` for `set_value/2`.

**Comment by jakobsvenning** [comment]
> This was resolved, it now always returns `ok` for `set_value/2`.

Awesome, then I'll close this issue 👍
