### ISSUE TITLE
Add before_end_processors to tracer record

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#223]
I'm not entirely sure about the error tuple as an option for its return value:

```erlang
-record(tracer,
        {
         module                        :: module(),
         on_start_processors           :: fun((otel_ctx:t(), opentelemetry:span()) -> opentelemetry:span()),
         before_end_processors         :: fun((opentelemetry:span()) -> opentelemetry:span() | {error, term()}),
         on_end_processors             :: fun((opentelemetry:span()) -> boolean() | {error, term()}),
         sampler                       :: otel_sampler:t(),
         instrumentation_library       :: otel_tracer_server:instrumentation_library() | undefined,
         telemetry_library             :: otel_tracer_server:telemetry_library() | undefined,
         resource                      :: otel_resource:t() | undefined
        }).
```

Assuming that's OK, though, in `otel_tracer_server.erl` I imagine we could:

```erlang
init(Opts) ->
  %% ...
    Tracer = #tracer{module=otel_tracer_default,
                     sampler=SamplerFun,
                     on_start_processors=on_start(Processors),
                     before_end_processors=before_end(Processors),
                     on_end_processors=on_end(Processors),
                     resource=Resource,
                     telemetry_library=TelemetryLibrary},
```

… though we should filter out those `Processors` that lack a `before_end`, and:

```erlang
before_end(Processors) ->
    fun(OriginalSpan) ->
            lists:foldl(fun(_, {error, Reason}) -> {error, Reason};
                           ({P, Config}, ModifiedSpan) -> P:before_end(ModifiedSpan, Config)
                        end, OriginalSpan, Processors)
    end.
```

… and by well it's obvious I don't know the slightest thing about Erlang, and I'm not sure what to modify next.

**Comment by garthk** [comment]
See prior discussion: https://github.com/open-telemetry/opentelemetry-specification/issues/1089#issuecomment-709046493

I note @Oberon00 suggested using “the” exporter wrapper for attribute sanitisation and anything else that doesn't need time- and process-locality, which might squeak me by for now on my blocking concern. Do we have one of those?

**Comment by tsloughter** [comment]
Closing this because I don't think BeforeEnd will ever be in the spec and I'd rather do this with added functionality in batch/simple processors to update the copy of the span in OnEnd anyway -- called "decorators" in the spec.

**Comment by garthk** [comment]
Yeah, fair enough.
