### ISSUE TITLE
otel_propagator round trip turns binary keys and values into character lists

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#224]
This is surprising, and could cause bugs if people call `set` after propagation with a binary key they expected to override.

```elixir
OpenTelemetry.Baggage.clear()       
OpenTelemetry.Baggage.set("key", "value")
OpenTelemetry.Baggage.get_all()                  # %{"key" => "value"}
text_map = :otel_propagator.text_map_inject([])  # [{"baggage", 'key=value'}]
OpenTelemetry.Baggage.clear()    
:otel_propagator.text_map_extract(text_map)
OpenTelemetry.Baggage.set("key", "value2")
OpenTelemetry.Baggage.get_all()                  # %{'key' => 'value', "key" => "value2"} <---- surprise!
:otel_propagator.text_map_inject([])             # [{"baggage", 'key=value2,key=value'}]
```

**Comment by tsloughter** [comment]
Good catch. Guess we need to convert keys to lists at time of `set`.

**Comment by garthk** [comment]
Given the spec for the header insists on valid UTF-8 string values before URI-encoding, might binaries be a better choice for the internal representation? `uri_string:compose_query/1` and ` uri_string:dissect_query/1` mentioned in #225 also work well with binary keys and values. This is `true`:

```erlang
Input = [{"k2", "v2,k3=b3😕"}],
Encoded = uri_string:compose_query(Input), 
Output = uri_string:dissect_query(Encoded), 
Output == Input.
```

**Comment by tsloughter** [comment]
I don't remember why I chose list string. Will have to try to figure that out but likely binary should be used.

**Comment by ferd** [comment]
Yeah with the spec insisting on UTF-8, binaries are the safest bet. I don't like the idea of having utf8-as-strings when all the stdlib functions will handle these as codepoints.

**Comment by tsloughter** [comment]
Closing since #233 is merged.
