### ISSUE TITLE
FunctionClauseError trying to use Tracer.with_span as a one-liner

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#235]
```plain
iex(8)> Tracer.with_span "span-1", attributes: [], do: 1
** (FunctionClauseError) no function clause matching in OpenTelemetry.Tracer."MACRO-with_span"/4    
```
… because the `do` block gets pulled into the `span_opts`. Workaround is to stick to the map:
```plain
iex(8)> Tracer.with_span "span-1", %{attributes: []}, do: 1
1
```

**Comment by tsloughter** [comment]
What's the issue for? It is an oddity of elixir, are you opening this to consider reverting the lists support or to have docs added that mention thi?

**Comment by garthk** [comment]
I didn't think the macro through enough when adding the lists support. I think for this one I'm going to fix it rather than back out the earlier change or wallpaper over it with documentation.

**Comment by tsloughter** [comment]
But how would you fix it? It is just an quirk of Elixir, isn't the only option is to move  `start_opts` to the last argument?

**Comment by garthk** [comment]
The macro's argument is an AST, and the representations of lists and 2-tuples and these atoms are lists and 2-tuples and the same atoms, so we can just pop the block out:
```elixir
defmodule Demo do
  defmacro with_span(name, start_opts) when is_list(start_opts) do
    {block, start_opts} = Keyword.pop!(start_opts, :do)
    quote do
      IO.inspect(unquote(start_opts), label: unquote(name))
      unquote(block)
    end
  end
end

import Demo
with_span "test1", do: IO.puts("ok!")
with_span "test2", attributes: [], kind: :client, do: IO.puts("ok!")
```
outputs
```plain
test1: []
ok!
test2: [attributes: [], kind: :client]
ok!
```

**Comment by bryannaegele** [comment]
I'm not sure why we'd go to such lengths when the example is addressed by simply not relying on keyword magic of omitting the brackets.

`Tracer.with_span "span-1", [attributes: []], do: 1`

It should also work by not omitting parens.

`Tracer.with_span("span-1", attributes: []), do: 1`

**Comment by garthk** [comment]
Oh, just trying to make the first thing they write work. I'm also trying to get the formatter to let me leave the parens out, but noooo.

**Comment by tsloughter** [comment]
Yea, probably better not to do all the hacking. I'd say revert it but I'd be ok with instead always using the `[]` version in code examples to help avoid confusion even more. As in, even this:

```elixir
Tracer.with_span "span-1", [attributes: []] do
  1
end
```

**Comment by tsloughter** [comment]
Should I close this? There isn't really a fix here because there is both `with_span/3` and `with_span/4` otherwise I'd be curious about doing the hack fix that combined start opts and do block.
