### ISSUE TITLE
Generate semantic conventions from yaml

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#241]
Semantic conventions have been updated: https://github.com/open-telemetry/opentelemetry-specification/pull/1598

We should switch to generating the Erlang macros of keys and values from the yaml so any changes to the names like this just requires regenerating the header file of macros.

A problem is many of the semantic conventions are to be used by third party libraries which are sometimes Elixir and Elixir can't reference Erlang macros. May have to additionally generate Elixir functions or some other structure that represents these keys and values.

**Comment by bryannaegele** [comment]
Seems like there were just consistency problems in that PR versus major changes.

Outside of all the ones that get passed in by the env vars, is there anywhere else we're actually using these labels?

**Comment by tsloughter** [comment]
These are mostly (or completely) separate from resources passed in as env vars. There is code in otel that is detecting stuff like what OS it is running on and then should be contrib/third party libs that are able to detect and set like what kubernetes namespace it is running in.

**Comment by tsloughter** [comment]
We need a separate application for this. That way resource detectors and instrumentation libraries can depend on that library to get the constants needed for semantic conventions they must adhere to.

**Comment by tsloughter** [comment]
Was completed and package published https://github.com/open-telemetry/opentelemetry-erlang/tree/main/apps/opentelemetry_semantic_conventions
