### ISSUE TITLE
Add functions for creating a new tracer

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#271]
Currently you can set a tracer for a named tracer but configuration (beyond setting the module to use) is basically hidden since it requires creating an `otel_tracer` record which is in `src/` and not `include/`.

I think functions for creating a tracer record from arguments and setting/getting particular fields is needed.

**Comment by kamilkowalski** [comment]
I'm new to this codebase so pardon my ignorance, but do you mean functions for internal use or being part of the public API? According to [the Tracing SDK spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#tracer-creation), the `TracerProvider` should be responsible for all configuration, and any changes to that configuration should be reflected in `Tracer`s created by the given `TracerProvider`. Based on this I would imagine a set of configuration functions in `otel_tracer_server` - e.g. `set_sampler/1`) to update the `TracerProvider` config at runtime, and `get_sampler/0` to fetch it (although I don't see a good use case for that, [the Node.js SDK only supports updating the config](https://open-telemetry.github.io/opentelemetry-js/classes/_opentelemetry_sdk_node.NodeSDK.html#configureTracerProvider) for example).

**Comment by tsloughter** [comment]
@kamilkowalski yes, it is from the provider. There is another issue I opened #278 which relates to this and they should probably be combined/this one closed.

What is needed is first the ability to create specific providers and set them to be used by particular apps or modules, as well as the ability to use a provider to create a tracer.

Your example would change it for some existing provider, which as it is today would be the default one and thus change this for everything, but the problem I wanted to address here is when a tracer with a different sampler from the default is required -- meaning a provider configured with a different sampler is required.

Also note that we do not follow the requirement of configuration changes having to be reflected in already created tracers. We have no efficient way of doing this and I'm still undecided if it is worth pushing for an update to the spec to allow this or to just break from the spec.

**Comment by tsloughter** [comment]
And I'm not familiar with the Node.js SDK, does their API not allow the creation of multiple TracerProviders? That this might be unsupported in some implementations came up in the maintainers meeting on Monday.

**Comment by tsloughter** [comment]
TracerProvider has been reworked in recent PRs, I'm closing this issue.
