### ISSUE TITLE
How to configure providers and select per-application/module

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#278]
Users should be able to set the tracer to be used by any application or module in their release. This is how they'll be able to set a specific sampler for an application to use for example.

Right now this is not straight forward. I would like it to be possible both through code and configuration but there is not a way to configure tracer providers (or which apps/modules should use them) in configuration.

My initial thought is that a configuration on `opentelemetry` can be added for providers that are made in addition to the default provider and to set applications/modules to use each:

```erlang
{opentelemetry, [{tracer_providers, #{my_tracer_provider => #{}}}]}
```

A couple questions come up with this: Today the configuration for the default tracer provider is done at the top level of `opentelemetry` application environment, like:

```erlang
{opentelemetry, [{sampler, {parent_based, #{root => always_on}}}]}
```

Would this be moved to under `tracer_providers`?

```erlang
{opentelemetry, [{tracer_providers, #{default => #{sampler => {parent_based, #{root => always_on}}}}]}
```

Or keep default configuration at the top and not have any special meaning to a key `default` in `tracer_providers` map.

Next, how to configure an application or module to use a specific provider? Is it configuration in the map of configuration for the `tracer_provider` or a separate top level configuration entry like, `{application_tracer_provider, [{my_app, my_tracer_provider}]}`?

I'm sure there are a number of other questions...

Good thing is this won't be a breaking change if we want to wait to add this or to extend it after releasing a stable 1.0. But if we get quick concensus I think it can make the stable 1.0 release at least.

**Comment by hauleth** [comment]
IIRC we are using macros in both Elixir and Erlang. Then we can do filtering per-module by passing module as a metadata by default. Then we can select provider on per-module level and setting provider for whole application will set it for all modules listed in `application:get_key(Application, modules)`. Of course that may fail in case of dynamically created modules, but I think it is so rare case that we shouldn't bother (also if someone is doing such magic, then they should expect it to work "weird").

**Comment by hauleth** [comment]
BTW that is how `logger:(un)set_module_level` is working.

**Comment by tsloughter** [comment]
Yes, we do use macros in both, and it actually does already do what you mention. The name of the module is used to lookup the tracer. The issue is how to configure the tracer provider and tracer in the first place. Also, the lookup is to get the tracer, not the provider, the provider creates a named tracer with its configuration. When a lookup is done it should return a tracer that was already created with the provider.

**Comment by tsloughter** [comment]
Ah dammit, that is a good point about logger. I say, dammit, because moving configuration will then break all existing configurations...

**Comment by hauleth** [comment]
We can accept it and translate to "new" approach while issuing the warning log at the same time.

**Comment by tsloughter** [comment]
I'm closing this as irrelevant, at least at this time. The use of providers this way is not likely the way to move forward but instead to have multiple tracer configurations stored in a single provider.
