### ISSUE TITLE
Move website_docs back to website repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-erlang#280]
As discussed at the [Sept 9 Comms][cm] and [Sept 13 Maintainers][mm] meetings, @open-telemetry/erlang-maintainers have a choice to make regarding **how your docs** ([website_docs]) will be incorporated into **[opentelemetry.io]**.

For your **two choices** and other details, see https://github.com/open-telemetry/opentelemetry.io/issues/730. 

The Comms team can help implement either of these choices. We'd appreciate a **response by Oct 1**, after which we'll **assume** that you're ok with option (2) and initiate the **move  of [website_docs] back to [website repo][wr]**.

/cc @austinlparker @open-telemetry/erlang-approvers

[website_docs]: https://github.com/open-telemetry/opentelemetry-erlang/tree/main/website_docs
[opentelemetry.io]: https://opentelemetry.io/
[cm]: https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY/edit#heading=h.brwue8g3voai
[mm]: https://docs.google.com/document/d/14lBtLAdzsV7M8xQNdhTJ0d2PxM1R7FByw-GttKJzVVw/edit#heading=h.vannhusrul2x
[wr]: https://github.com/open-telemetry/opentelemetry.io/

**Comment by tsloughter** [comment]
Oh great, I was meaning to ping someone about this. I guess if moving it to the website repo is the easiest (no submodules involved) we should just go with that.

**Comment by chalin** [comment]
Yes, it is the simplest and most flexible option.

**Comment by chalin** [comment]
/assign @chalin 
Moving ahead with this now.
