### ISSUE TITLE
TC Review of Trace API / SDK

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-erlang#299]
This tracks the status of the TC review for 1.0 Trace release of OpenTelemetry C++

## Status

- [x] Review [Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md)
  - [x] Traces
  - [x] Baggage
  - [x] Resource
  - [x] Context Propagation
  - [x] Environment Variables
  - [x] Exporters
- [x] Review [Versioning and Stability](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md) policy enforcement
  - [x] API
  - [x] SDK
- [x] Ensure Consistent names across implementation
- [X] Avoid confusions across implementation (e.g. same public API has different behaviors)
- [x] Ensure no experimental features (signals) are part of the released packages (e.g. api, sdk, etc.).

## Open TODOs / Cleanups

- [ ] Determine whether baggage should "merge" with previous, or overwrite
- [ ] Limits (of all sorts) Should be configurable by users.  The Specification (today) requires environment variables.  This is somewhat critical for instrumentation author vs. operations divides where someone writing instrumentation may aggresively add labels and then operators need to deal with fallout of having too-many and needing to limit for performance (or stability) reasons.
  - [x] #324
  - [x] #323
  - [x] #322
  - [x] #321
  - [x] #320
  - [x] #319
  - [x] #318
  - [x] #317

## Optional Cleanup TODOs

- Jaeger exporter should fast-follow GA.  Looks like it can be added in a non-breaking way
- HTTP OTLP exporter retries.

See https://github.com/open-telemetry/opentelemetry-specification/pull/1418 for process details.

**Comment by bryannaegele** [comment]
Just doing some organization over to issues.

**1.0 GA Items**

- [ ] Simple Span Processor
- [ ] IdGenerators
- [ ] Size limits:
  - [ ] events collection size limit
  - [ ] attribute collection size limit
  - [ ] links collection size limit
- [ ] SpanLimits
- [ ] Attribute Limits
- [ ] Environment Variables:
  - [ ] =OTEL_SERVICE_NAME=
  - [ ] =OTEL_EXPORTER_ZIPKIN_*=
  - [ ] limits
- [ ] Schema URL
- [ ] Resource detectors populate Schema URL

**Post 1.0 GA Items - Exporters**

- [ ] OTLP/HTTP JSON Protobuf Exporter
- [ ] OTLP/HTTP gzip Content-Encoding support
- [ ] Concurrent sending
- [ ] Honors retryable responses with backoff
- [ ] Honors non-retryable responses
- [ ] Honors throttling response
- [ ] Multi-destination spec compliance
  - [x] grpc
- [ ] SchemaURL in ResourceSpans and InstrumentationLibrarySpans
- [ ] Zipkin:
  - [ ] InstrumentationLibrary mapping
  - [ ] Error Status mapping
  - [ ] Integer microseconds in timestamps
- [ ] Jaeger

**Comment by tsloughter** [comment]
I've been procrastinating on limits again because they are a little annoying.

They are yet another global configuration that I guess I have to shove in a persistent term to be read every time a span operation is done.

I wish these, like a number of other things (like propagators, which won't be configurable per-library like other stuff if Tracers become configurable per instrumentation library) were just part of the Tracer and modifying Spans went through the Tracer, but they aren't.

But I will knock it out this week I guess.

**Comment by jsuereth** [comment]
AFAIK - span limits don't *need* to change post-startup.  Is that an expectation in erlang?

**Comment by bryannaegele** [comment]
Nah. We just have no limits at all right now

**Comment by tsloughter** [comment]
Closing, 1.0 was released a month ago. Thanks everyone!
