### ISSUE TITLE
OTLP exporter sends requests even when there are no spans

### ISSUE THREAD

**Issue by indrekj** [open-telemetry/opentelemetry-erlang#305]
I set `OTEL_TRACES_SAMPLER="always_off"` and noticed that the exporter is still making requests. Turns out that the exporter doesn't check if there are any spans or not, it always sends a request. Probably could use a guard [here](https://github.com/open-telemetry/opentelemetry-erlang/blob/c47a3f2796ae152b5b9d225ac66c543d30953b70/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl#L142) and [here](https://github.com/open-telemetry/opentelemetry-erlang/blob/c47a3f2796ae152b5b9d225ac66c543d30953b70/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl#L162).

**Comment by tsloughter** [comment]
I was thinking the processor should do the check so it only has to be done in one place and not in each exporter.

**Comment by tsloughter** [comment]
Oh, but you are right, there should also be a check in the exporter because spans can be dropped there if they have issues like failing to encode. So we should have both.

**Comment by tsloughter** [comment]
Keeping this open since #307 only addressed if the span table is empty and not if the OTLP exporter drops all spans for formatting reasons.
