### ISSUE TITLE
missing Tracer. set_status/2

### ISSUE THREAD

**Issue by dvic** [open-telemetry/opentelemetry-erlang#311]
Currently `Tracer.set_status` is defined as:

```elixir
  @spec set_status(OpenTelemetry.status()) :: boolean()
  def set_status(status) do
    :otel_span.set_status(:otel_tracer.current_span_ctx(), status)
  end
```

Shouldn't this function accept an optional description message? (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status)

**Comment by bryannaegele** [comment]
@dvic you aren't allowed to set messages on non-error statuses. When you create an error status with an optional message, it is set appropriately on the span.

**Comment by tsloughter** [comment]
But also the status is a record, so you must first create the status with `OpenTelemetry.status/2` and then pass it to `set_status`.
