### ISSUE TITLE
traceparent header with multiple values results in invalid parent span id

### ISSUE THREAD

**Issue by dvic** [open-telemetry/opentelemetry-erlang#312]
What does it mean when the traceparent has multiple values? I'm encountering an issue with this kind of situation where the exported parent span id of a child span in another service is incorrect (it does not exist in the parent service). Are there any tests for this situation? I had a quick glance but I couldn't find any.

An example header from the logs:
```
{"traceparent",
   "00-bbe28300b6d6f39067b9ec48e57f5352-2ec545402da1a36c-01, 00-bbe28300b6d6f39067b9ec48e57f5352-1d449be79eea12cf-01"}
```

**Comment by tsloughter** [comment]
You are receiving a traceparent with multiple values in your code or you are finding your code to be sending multiple values?

**Comment by dvic** [comment]
The former, I observed that the called service had two values while the "sender" only injected one. I will double check tonight and try to reproduce it in an example repo .

**Comment by dvic** [comment]
I haven't been able to reproduce it in a separate repo, so it is something really specific to our setup, maybe the a certain combination with the `opentelemetry_oban` library is causing this behavior. Will dive further into this tomorrow and report any updates here.

**Comment by tsloughter** [comment]
Are these all elixir services?

Not sure how it could happen unless the sender is sending 2 traceparent headers.

**Comment by dvic** [comment]
I found the cause, it's not a bug, it's a stupid mistake on my side 😳

We switched from Finch to Tesla, and while with Finch we had to manually insert the trace headers, with Tesla we are using middleware for this, so the header was being set twice. Sorry for the noise.
