### ISSUE TITLE
Map values dropped from exception attributes in 1.0.0-rc.4

### ISSUE THREAD

**Issue by aaronrenner** [open-telemetry/opentelemetry-erlang#339]
I'm working on a PR to update [opentelemetry_liveview](https://github.com/qdentity/opentelemetry_liveview) to be compatible with 1.0.0-rc.4 and I'm found a test that simulates a bad key error that previously passed but doesn't anymore.

https://github.com/qdentity/opentelemetry_liveview/blob/3f14bcbc39f321170fca2b51477c51adb15aa1ee/test/opentelemetry_liveview_test.exs#L74-L94

After some troubleshooting I've found that `Span.record_exception/4` is being called like this:

```elixir
Span.record_exception(ctx, normalized_exception, stacktrace, attrs)

# attrs is [key: :name, map: %{username: "foobar"}]
```
This ends up reporting the following:
```elixir
%{
  :key => :name,
  "exception.message" => "Erlang error: :badkey",
  "exception.stacktrace" => _stacktrace,
  "exception.type" => "Elixir.ErlangError"
}
```
but drops the `:map` attribute which is likely because of the complex value.

Since this worked previously in 1.0.0-rc.2 I wanted to check is change in behavior desired? Here is a patch that reproduces the test failure:

```patch
diff --git a/test/otel_tests.exs b/test/otel_tests.exs
index db7b8a8..91e48ef 100644
--- a/test/otel_tests.exs
+++ b/test/otel_tests.exs
@@ -235,7 +235,7 @@ defmodule OtelTests do
       raise RuntimeError, "my error message"
     rescue
       ex ->
-        assert Span.record_exception(s, ex, __STACKTRACE__)
+        assert Span.record_exception(s, ex, __STACKTRACE__, [map: %{user_id: 1}])
         assert Span.end_span(s)
 
         stacktrace = Exception.format_stacktrace(__STACKTRACE__)
@@ -245,7 +245,8 @@ defmodule OtelTests do
             [
               {"exception.type", "Elixir.RuntimeError"},
               {"exception.message", "my error message"},
-              {"exception.stacktrace", stacktrace}
+              {"exception.stacktrace", stacktrace},
+              map: %{user_id: 1}
             ],
             128,
             :infinity
```
(also available to try out on this branch https://github.com/aaronrenner/opentelemetry-erlang/tree/ar-repro-dropped-exception-attribute)

**Comment by tsloughter** [comment]
Yes, it is desired. Attribute values must be primitive types or a list of primitive types. How were you exporting/using this data before that it wasn't useful to send a map as a value?

**Comment by aaronrenner** [comment]
Oh, good to know... I just found what you're referring to in [the spec](https://opentelemetry.io/docs/reference/specification/common/common/#attributes). I think the idea was to allow the user to see both the key name and the map that were thrown as part of an `:badkey` error, but if we want to continue that behavior it looks like the recommendation is to encode the map to JSON.

Thanks for your help!

**Comment by tsloughter** [comment]
Yup, sorry, I should have linked to the spec. The encoding to json string is recommended just for protocols that don't support arrays as attribute values. Not to say that isn't a good solution for you.

And now that I'm rereading this issue with fresh eyes I wonder if Elixir has a way to format an exception as a string that includes the argument? Erlang recently added new functionality for pretty printing stacktraces and including more information, figure maybe Elixir could have already had something like that?
