### ISSUE TITLE
opentelemetry exporter default config result in faulty trace endpoint

### ISSUE THREAD

**Issue by calvin-kargo** [open-telemetry/opentelemetry-erlang#377]
Environment:
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 24)

Dependency:
"opentelemetry": {:hex, :opentelemetry, "1.0.2",
"opentelemetry_api": {:hex, :opentelemetry_api, "1.0.2"
"opentelemetry_exporter": {:hex, :opentelemetry_exporter, "1.0.2"

Based opentelemetry readme, default endpoint should send spans to `http://localhost:4318/v1/traces`:
>By default the exporter will use HTTP to export protobuf encoded Spans to http://localhost:4318/v1/traces.

However, when there's no config at all set for opentelemetry, opentelemetry exporter doesn't send to `http://localhost:4318/v1/traces` (it seems sending to `http://localhost:4318`), resulting in error like `error response from service exported to status=404 404 page not found`

Here's contrast state of opentelemetry_exporter after init, with config, path `v1/traces` is set right.
without config:
```
iex(20)> :opentelemetry_exporter.init(%{})
{:ok,
 {:state, :http_protobuf, :undefined, [], :undefined, :undefined,
  [
    %{
      host: 'localhost',
      path: [],
      port: 4318,
      scheme: 'http',
      ssl_options: [
```

with config:
```
# releases.exs
config :opentelemetry_exporter,
  otlp_protocol: :http_protobuf,
  otlp_endpoint: "http://localhost:4318"

iex(2)> :opentelemetry_exporter.init(%{})
{:ok,
 {:state, :http_protobuf, :undefined, [], :undefined, :undefined,
  [
    %{
      host: "localhost",
      path: "/v1/traces",
      port: 4318,
      scheme: "http",
```

**Comment by tsloughter** [comment]
I think this is fixed in `main` actually, have you tried the latest?

**Comment by calvin-kargo** [comment]
I just tried latest, and the issue of `opentelemetry_exporter.init(%{})` path is `[]` when there is no config persisted @tsloughter

**Comment by tsloughter** [comment]
@calvin-kargo hm, ok, thanks, I'll take a look today.

**Comment by tsloughter** [comment]
Aaah, I misread the issue and thought you were getting `[]` path when you set `otlp_endpoint`, not when it was using the default.

Now I see the source of the issue, though am confused why I did it this way in the first place, maybe originally it was appending the default path and so I kept the default endpoint with a path of `[]`... either way, I'm opening a PR.
