### ISSUE TITLE
Not able to use custom propagator via config

### ISSUE THREAD

**Issue by ananthakumaran** [open-telemetry/opentelemetry-erlang#396]
I am not sure if this is an actual issue or if I am just not calling the correct API. I am planning to use sentry as our trace collector and interop with sentry clients written in other languages. Sentry uses a [sentry-trace](https://develop.sentry.dev/sdk/performance/#header-sentry-trace) HTTP header which is similar to `traceparent`. I figured, I could just write my own propagator and tried to enable it via config below

```
config :opentelemetry,
  text_map_propagators: [:otel_propagator_sentry],
```

But, the custom propagator just gets ignored with a warning

```
[warn] Ignoring unknown propagator otel_propagator_sentry in OS environment variable $OTEL_PROPAGATORS
```

From https://github.com/open-telemetry/opentelemetry-erlang/pull/110, it seems like custom propagator was supported?

**Comment by ananthakumaran** [comment]
I just removed the warning https://github.com/ananthakumaran/opentelemetry-erlang/commit/eae8041aeaf3b34ad300949ea4c01bdedae3a907 and returned the module. It has been working without any issue.

```
config :opentelemetry,
  text_map_propagators: [OpentelemetrySentry.Propagator]
```
I want to get it fixed here. Could I just open a PR with the above commit?

**Comment by tsloughter** [comment]
Yup, a PR would be great, thanks!
