### ISSUE TITLE
using endpoint URL and top level ssl_options in exporter config causes error

### ISSUE THREAD

**Issue by kenichi** [open-telemetry/opentelemetry-erlang#417]
When configuring opentelemetry_exporter 1.0.4 for client mTLS (issued certificate and private key), setting a single URL value for the endpoint and top level `ssl_options` causes an error and no data is sent to the endpoint.

example config:
```elixir
config :opentelemetry_exporter,
  otlp_protocol: :http_protobuf,
  otlp_endpoint: "https://example.com:4318",
  ssl_options: [cert: ..., key: ...]
```

example error:
```
[warning] OTLP exporter failed to initialize with exception :error::function_clause
```

expected data to be sent to the endpoint authorized by client cert and to see output:
```
[info] OTLP exporter successfully initialized
```

NOTE:

Using a map instead of a URL and moving the ssl_options there *does* work, but this should not be needed.

```elixir
config :opentelemetry_exporter,
    otlp_protocol: :http_protobuf,
    otlp_endpoint: %{
      scheme: "https",
      host: "example.com",
      port: 4318,
      ssl_options: ssl_options
    }
```

See also: https://cloud-native.slack.com/archives/C01N75YMZCN/p1658942572382929

**Comment by kenichi** [comment]
```
[debug] OTLP exporter failed to initialize: exception error: no function clause matching
        opentelemetry_exporter:append_path({error,invalid_uri,"\""}) (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter.erl, line 441)
  in function  opentelemetry_exporter:endpoints_append_path/1 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter.erl, line 439)
  in call from opentelemetry_exporter:update_opts/6 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter.erl, line 462)
  in call from opentelemetry_exporter:merge_with_environment/1 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter.erl, line 409)
  in call from opentelemetry_exporter:init/1 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter.erl, line 161)
  in call from otel_exporter:init/1 (/app/deps/opentelemetry/src/otel_exporter.erl, line 42)
  in call from otel_batch_processor:idle/3 (/app/deps/opentelemetry/src/otel_batch_processor.erl, line 137)
  in call from gen_statem:loop_state_callback/11 (gen_statem.erl, line 1203)
```

**Comment by tsloughter** [comment]
It looks like the issue is the value it is trying to parse as the endpoint is confusing it. Can you share the actual endpoint string you used in your config and verify you don't have anything set in the environment variable `$OTEL_EXPORTER_OTLP_ENDPOINT`?

**Comment by kenichi** [comment]
Ah thanks good eye, my bad - this was compose handling quoted URL string in the env file raw and setting the value in the container with the actual quotes 🤦🏽‍♂️ 

`{error,invalid_uri,"\""}` should have clued me in.

**Comment by tsloughter** [comment]
@kenichi ah ok. We should have a better error though, it shouldn't just pass the error tuple to the `append_path` function.

**Comment by kenichi** [comment]
@tsloughter I got some time to take a closer look at this. It does seem it was ignoring `ssl_options` set in the app env, and passing the app env endpoint value through without much checking. What do you think of [these](https://github.com/open-telemetry/opentelemetry-erlang/compare/main...kenichi:opentelemetry-erlang:app_env_ssl_options) changes?  Disclaimer: first erlang. I'm not quite sure of the behavior of some of the tests, but tried only to address these two issues. I also tested with an app using these changes against the 1.0.4 tag, and got mTLS to work with this config:

```elixir
ssl_options = [cert: "...", key: "..."] ++ :tls_certificate_check.options("example.com")

config :opentelemetry_exporter,
  otlp_endpoint: "https://example.com:4318",
  ssl_options: ssl_options

```

**Comment by tsloughter** [comment]
Nice, those changes look good. I think the `LOG_ERROR` should probably be `LOG_WARNING` tho, since there could be multiple endpoints. 

This is better than the solution I started are on that involved deeper changes in the `transform` function :)

**Comment by tsloughter** [comment]
And if you wanted to be extra awesome, including that example config in the readme docs would be very useful to people I think :)

**Comment by kenichi** [comment]
ok, i've made the changes and will open a PR. thanks!
