### ISSUE TITLE
Try Result/Observe based Async Metrics API

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#441]

**Comment by tsloughter** [comment]
One thought I have is basically doing `pmap` without the `p` at first. So each callback gets run and when it calls `otel_observer:result(Name, Attributes, Number)` a message is sent to `self()`. After all callbacks are run it collects the results.

After saying that I realize when switching from `self()` to it collecting in a parent process it'll be better to use either a `fun` or another record as an arg. Like:

```
Observe(Name, Attributes, Number)

%% or

otel_observer:result(Observer, Name, Attributes, Number)
```

Wanted thought from @ferd and @bryannaegele on this strategy.

I don't know why but I feel like requiring a return value of the callback to be a tuple list or map of `Name => {Number, Attributes}` to be error prone and the calling some sort of observe function being less so, but maybe I'm over thinking it.

**Comment by ferd** [comment]
I guess the key design elements in my mind are:
- is there only one observer per type of metric or can many exist for the same data points?
- does observation have any side-effect such as resetting counters?
- are the results reusable by many exporters?
- are there any restrictions on the interleaving of calls between observation, metrics update, exports, etc.?

**Comment by tsloughter** [comment]
* The Observer fun or record will be for all Instruments being recorded for that callback.
* Good question. It currently does the checkpointing (so resetting) after all callbacks have run, but maybe that will change with this change.
* The results are used by the Reader that runs the callback. Exporters are called by the Reader.
* Readers do the checkpointing and exporting, so no restriction, restrictions are handled by the Reader being a single process and managing the callbacks.

**Comment by tsloughter** [comment]
To be clear what the return value based approach would look like:

```
fun() ->
  [{Name, Attributes, Number}]
end
```

I assume Names of the Instrments just have to be known by the user writing the callback. I guess that would limit the ability to use the same callback function (not actually the same callback) for differently named Instruments if they want to have a custom name for the value recorded.. hm

Versus a function based approach:

```
fun(Observer) ->
  Observe(Name, Attributes, Number)
end
```

or

```
fun(Observer) ->
  otel_observer:result(Observer, Name, Attributes, Number)
end
```

**Comment by tsloughter** [comment]
So maybe it needs to be:

```
fun(CPUObserver, MemoryObserver) ->
  [{CPUObserver, Attributes, Number}, ...]
end
```

And:

```
fun(CPUObserver, MemoryObserver) ->
  CPUObserver(Attributes, Number),
  ...
end

%% or

fun(CPUObserver, MemoryObserver) ->
  otel_result:observe(CPUObserver, Attributes, Number),
  ...
end
```

**Comment by tsloughter** [comment]
Thinking about it some more I think I may be overthinking it in planning for the need to use different names for the same metric in a callback.

So adding user defined args that are passed to the callback allowing a generic one to be written probably makes more sense.
