### ISSUE TITLE
opentelemetry >= 1.1.0 should depend on opentelemetry_api >= 1.1.0

### ISSUE THREAD

**Issue by 23Skidoo** [open-telemetry/opentelemetry-erlang#446]
`opentelemetry` 1.1 depends on `opentelemetry_api` >= 1.0:
https://github.com/open-telemetry/opentelemetry-erlang/blob/aafd1f34e990967acb6d6786dca025680ef9f242/apps/opentelemetry/rebar.config#L2

However, it also refers to the type `instrumentation_scope`, which was added in `opentelemetry_api` 1.1:

https://github.com/open-telemetry/opentelemetry-erlang/blob/aafd1f34e990967acb6d6786dca025680ef9f242/apps/opentelemetry/src/otel_tracer_server.erl#L33
https://github.com/open-telemetry/opentelemetry-erlang/blob/aafd1f34e990967acb6d6786dca025680ef9f242/apps/opentelemetry/src/otel_tracer_server.erl#L38

This leads to a compile-time error when compiling `opentelemetry` against `opentelemetry_api` < 1.1:

```
===> Compiling opentelemetry
===> Compiling src/otel_tracer_server.erl failed
src/otel_tracer_server.erl:38:34: record instrumentation_scope undefined
```

**Comment by tsloughter** [comment]
Thanks, forgot to bump before publishing, I guess we need tests of the packages before/after publishing :)

**Comment by tsloughter** [comment]
I'll release 1.1.1 once the PR and a zipkin one is approved.
