### ISSUE TITLE
undefined function opentelemetry_zipkin:export/4

### ISSUE THREAD

**Issue by ulissesalmeida** [open-telemetry/opentelemetry-erlang#447]
Full stack-trace:

```
exporter threw exception: exporter=:opentelemetry_zipkin exception error: undefined function opentelemetry_zipkin:export/4
  in function  otel_batch_processor:export/3 (/build/deps/opentelemetry/src/otel_batch_processor.erl, line 369)
  in call from otel_batch_processor:send_spans/3 (/build/deps/opentelemetry/src/otel_batch_processor.erl, line 355)
```

- opentelemetry: 1.1.0
- opentelemetry_api: 1.1.0
- opentelemetry_zipkin: 1.0.0

In fact, the newer API is incompatible with latest version of `opentelemetry_zipkin`.

Here expects the module to have [`export/4`](https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry/src/otel_exporter.erl#L118-L119) but zipikin module exports [`export/3` function](https://github.com/open-telemetry/opentelemetry-erlang/blob/0bc0f4d38e387047b189915c81efe2fa42c0730b/apps/opentelemetry_zipkin/src/opentelemetry_zipkin.erl#L24)

**Comment by tsloughter** [comment]
Yup, thanks, I'll get this fixed.
