### ISSUE TITLE
Input checking

### ISSUE THREAD

**Issue by derekkraan** [open-telemetry/opentelemetry-erlang#476]
We are getting a lot of errors that look like this:

```
info [info] exporter threw exception: exporter=:opentelemetry_exporter exception error: bad argument
  in function  byte_size/1
     called as byte_size({error,<<"%PDF-1.4\n%">>,
                                <<"âãÏÓ\n7 0 obj\n<</Length 694/Filter/FlateDecode>>stream\nx"...>>})
     *** argument 1: not a bitstring
  in call from opentelemetry_exporter_trace_service_pb:e_type_string/3 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter_trace_service_pb.erl, line 942)
  in call from opentelemetry_exporter_trace_service_pb:e_mfield_key_value_value/3 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter_trace_service_pb.erl, line 870)
  in call from opentelemetry_exporter_trace_service_pb:e_mfield_event_attributes/3 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter_trace_service_pb.erl, line 778)
  in call from opentelemetry_exporter_trace_service_pb:e_field_event_attributes/3 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter_trace_service_pb.erl, line 784)
  in call from opentelemetry_exporter_trace_service_pb:encode_msg_event/3 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter_trace_service_pb.erl, line 315)
  in call from opentelemetry_exporter_trace_service_pb:e_mfield_span_events/3 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter_trace_service_pb.erl, line 811)
  in call from opentelemetry_exporter_trace_service_pb:e_field_span_events/3 (/app/deps/opentelemetry_exporter/src/opentelemetry_exporter_trace_service_pb.erl, line 817) 
```

I believe this is caused by invalid data being entered into otel (looks like via event attributes in this case).

As far as I know, the data shapes are very clear as to what is and is not acceptable input for the otel-erlang library, but this is not being checked at the moment a function is being called. This leads to errors surfacing much later, which is near impossible to debug.

Is my suspicion correct? The other alternative is that there is a bug in the otel_exporter_trace_service but I find that unlikely.

Generally we should check the input to our library carefully at the boundary, to prevent this kind of thing.

So I think this issue is really asking for: comprehensive input checking for public functions in this library.

I would be willing to help work on this if I had a good idea of where to start and confirmation that this is indeed the source of the issue. I do see some things that look like input checking but it's not entirely clear to me where they are insufficient or whether they are intended for this purpose.

**Comment by tsloughter** [comment]
@derekkraan I think this issue is resolved in `main`, tho could have missed a place.

What should happen is instead of setting a string it'll use a bytes field when the binary data is not valid utf8, which must be the case here since that is an error message given by `unicode:characters_to_binary`.

Any chance you could see if `main` works before I cut a release? In case I missed a place to make the fix.

**Comment by derekkraan** [comment]
Yes, I'll check that. Just the current `main` branch?
