### ISSUE TITLE
ot_span.start_opts needs start_time

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#5]
So often, the only way to find out whether anything has happened is just afterward.

See also: census-instrumentation/opencensus-erlang#157

**Comment by garthk** [comment]
Similar request for the spec: open-telemetry/opentelemetry-specification#139

**Comment by tsloughter** [comment]
There are other open issues/prs on OTel spec and RFCs for defining this so we'll wait until thoes are smoothed out. Good to poke your head into those discussions though and make sure the direction there is one that fits your needs.
