### ISSUE TITLE
Add Span decorators to Processors. Name suggestions?

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang#538]
Per the spec we can have Span "decorators" do modify the Span in the built-in processors. This still needs to be added.

They could be used for things like adding baggage to the Span attributes instead of using a separate Span Processor.

I don't like the name "decorator" for these in Erlang/Elixir since people equate those with decorating a function, so name suggestions would be helpful.

**Comment by albertored** [comment]
Is this still valid? I don't find anything about "Span decorators" in the spec?

**Comment by tsloughter** [comment]
Ah no, it isn't. The decorators were removed from the spec: https://github.com/open-telemetry/opentelemetry-specification/pull/3363

So I'll close this.
