### ISSUE TITLE
[Question]: How to disable/enable tracer(s) in runtime

### ISSUE THREAD

**Issue by jamars** [open-telemetry/opentelemetry-erlang#573]
Is it possible to disable/enable open-telemetry tracing while the application is running? I see the [spec](https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/#general-sdk-configuration) defines `OTEL_SDK_DISABLED` environment variable as

```Boolean value. If “true”, a no-op SDK implementation will be used for all telemetry signals. Any other value or absence of the variable will have no effect and the SDK will remain enabled. This setting has no effect on propagators configured through the OTEL_PROPAGATORS variable.```

As far as I could see there is no reference to this env var in the code.

**Comment by tsloughter** [comment]
We don't yet have `OTEL_SDK_DISABLED`. Should be simple enough to add, I can look at doing that soon, probably today.
