### ISSUE TITLE
Update OTLP to 0.20.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-erlang#597]
OTLP 0.20.0 was released: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.20.0

It is also the release candidate for upcoming 1.0.0.

Please update the OTLP exporter to use OTLP 0.20.0.

**Comment by tigrannajaryan** [comment]
@open-telemetry/erlang-maintainers can you please take a look and tell if v0.20.0 works for you? We are planning to declare OTLP 1.0 next week and any changes after that are going to be much harder (if not impossible).

**Comment by tsloughter** [comment]
PR opened https://github.com/open-telemetry/opentelemetry-erlang/pull/598

**Comment by tigrannajaryan** [comment]
@tsloughter I see https://github.com/open-telemetry/opentelemetry-erlang/pull/598 is now merged. I assume it means all is good and we can close this issue?

**Comment by tsloughter** [comment]
Yup, thanks!
