### ISSUE TITLE
broken typespec for otel_span:start_opts

### ISSUE THREAD

**Issue by RoadRunnr** [open-telemetry/opentelemetry-erlang#708]
@tsloughter commit e4c2c109 authored by you broke the typespec for the `Opts` argument of `otel_tracer:with_span` by changing all map members to mandatory, however in the API all of them are optional.

Declaring all map members as mandatory might be appropriate when the type is used for SDK functions, but for the API function all options are indeed optional. Please consider changing the type spec back and or use a different type for the SDK functions.

**Comment by tsloughter** [comment]
I'm guessing Eqwalizer complained which lead me to making this change. I'll fix it up like you sugggest.
