### ISSUE TITLE
Dynamic resources

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#73]
We need to send all events with specific attributes for correlation, suggesting we use OpenTelemetry resources… but for some of the attributes we need the values to be computed on the fly _eg._ for:

* Instance uptime
* RAM consumption and availability
* Disk consumption and availability
* CPU consumption and availability

We can't satisfy this need with metrics: to use our trace destination to correlate these against other measurements and metadata in our trace attributes, we need these to also be present in our span attributes.

I've got two obvious places to put this capability, both of which feel wrong:

* A wrapper around the OpenTelemetry API to make it more useful
* The exporter

Is there some place I could put it? A hook at span creation or completion would do the trick, or both if I wanted to do an adequate job for CPU consumption without needing to keep a log somewhere.

**Comment by tsloughter** [comment]
This is a use for span processors. If their capabilities aren't enough to make this possible then we need to change them until it is.

**Comment by tsloughter** [comment]
Closing this as there hasn't been anything new in a year.
