### ISSUE TITLE
Means to force export

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#74]
`:timer.sleep/1` in tests makes babies cry; any chance of an exported method to trigger export so we can verify the exporter worked?

**Comment by tsloughter** [comment]
With elixir if you can turn the export into a message (I'm assuming this is for honeycomb so you can't just use the `_pid` exporter?) and do `assert_receive` which takes a timeout.

In opentelemetry tests we are using a macro to do the same as `assert_receive` and in the case of testing zipkin and otel protocol I just manually call their `export` functions.

Definitely could use better testing on the zipkin/otpl side as it just verifies its an "ok" :):

```
?assertMatch(ok, opentelemetry_zipkin:export(Tid, Resource, State)),
```

**Comment by garthk** [comment]
Yeah, a receive was how I ended up doing it. It's replacing one timeout Sean didn't like with another he shouldn't, but not to worry :)
