### ISSUE TITLE
Expose `ot_tracer` record?

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#75]
I can't try `on_start_processors` and `on_end_processors` in a unit test to solve #73 without being able to call `:opentelemetry.set_default_tracer/1` with a `#tracer{}`, which I can't consume with `Record.extract/2` because it's not in `include`.

That's not _entirely_ true. I can save the environment, replace it, stop the app, restart it, run my test, stop it again, put back the old environment, and restart it again. You'll feel _awful_ when you review the code, though.

**Comment by tsloughter** [comment]
You need this accessible in another repo?

When it is just for a test the usual process is to include the header even if it isn't in the include directory.

**Comment by garthk** [comment]
Yeah, I'll work around it. :/
