### ISSUE TITLE
Can we get a release that dializes in elixir?

### ISSUE THREAD

**Issue by scohen** [open-telemetry/opentelemetry-erlang#763]
Under 1.4.0, dialyzer emits an error (at least in elixir) because the options passed to `OpentelemetryTelemetry.start_telemetry_span/4` require all fields to be present. It looks like #717 fixes this, but it doesn't look like these changes were incorporated into 1.4.0. 

Can we get a 1.4.1 that incorporates these changes?

**Comment by tsloughter** [comment]
Will make today.

**Comment by scohen** [comment]
Thank you very much!

**Comment by tsloughter** [comment]
Published: https://hex.pm/packages/opentelemetry_api/1.3.1
