### ISSUE TITLE
undefined function opentelemetry_exporter:export/3 after upgrading opentelemetry

### ISSUE THREAD

**Issue by davidjulien** [open-telemetry/opentelemetry-erlang#784]
Hello!

After upgrading `opentelemetry` from version 1.4.0 to 1.4.1  and `opentelemetry_api` from version 1.3.1 to 1.3.2, I have now this error during execution:

```
span exporter threw exception: exporter=:opentelemetry_exporter exception error: undefined function opentelemetry_exporter:export/3
  in function  otel_batch_processor:export/3 (/app/deps/opentelemetry/src/otel_batch_processor.erl, line 444)
  in call from otel_batch_processor:send_spans/3 (/app/deps/opentelemetry/src/otel_batch_processor.erl, line 430)
```

My versions of opentelemetry libs seems up-to-date:
opentelemetry           1.4.1
opentelemetry_api       1.3.2  
opentelemetry_cowboy    0.3.0
opentelemetry_ecto      1.2.0
opentelemetry_exporter  1.7.0
opentelemetry_phoenix   1.2.0

Do I miss something during the upgrade? Changelog doesn't seem to mention a special action before upgrading.

Thanks

David

**Comment by davidjulien** [comment]
Upgrading `opentelemetry_api` only doesn't trigger the bug.

**Comment by tsloughter** [comment]
@davidjulien sorry, yes, this is a bug in the latest packages. I'll publish a new exporter that should resolve it.

We need CI that doesn't test against the entire repo but instead based on the version constraints to catch stuff like this...

**Comment by tsloughter** [comment]
Well that and this should have been minor release bumps and I think mix would have caught it :(

**Comment by tsloughter** [comment]
Retiring those packages to make sure I get this right and making new releases as soon as I can this morning.

**Comment by davidjulien** [comment]
Thank you @tsloughter!

**Comment by davidjulien** [comment]
Tested this morning. No bug detected anymore. Thank you for your reactivity! Have a nice week.
